### DISCUSSION TITLE
Command

### DISCUSSION THREAD

**Discussion by rafaelpirolla** [ansible-community/molecule-docker#89] [Q&A]
https://github.com/ansible-community/molecule-docker/blob/5ebda29420c073ed9f6f1caed2f7f3f998361ff5/molecule_docker/playbooks/create.yml#L109

Maybe just do a:
`when: item.command`

There's something off with this task though. Sorry that I don't know how to be more precise.

If you just take the create out and try to run it with a simple variable definition it shouts strange issues since the with_item seems to point to a result dict and not the platform itself.

You would also need to create the filter file... Executing this would give:
```
TASK [Determine the CMD directives] ********************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": 
"The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'name'

The error appears to be in 'docker.yml': line 107, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: Determine the CMD directives
       ^ here
 "}
```
```
---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.docker
  vars:
    molecule_labels:
      owner: molecule
    platforms:
      - name: "redis"
        image: "redis"
        privileged: true
        pre_build_image: true
        exposed_ports:
          - "6379:6379"
        tty: true
  tasks:
    - name: Log into a Docker registry
      docker_login:
        username: "{{ item.registry.credentials.username }}"
        password: "{{ item.registry.credentials.password }}"
        email: "{{ item.registry.credentials.email | default(omit) }}"
        registry: "{{ item.registry.url }}"
        docker_host: "{{ item.docker_host | default(lookup('env', 'DOCKER_HOST') or 'unix://var/run/docker.sock') }}"
        cacert_path: "{{ item.cacert_path | default((lookup('env', 'DOCKER_CERT_PATH') + '/ca.pem') if lookup('env', 'DOCKER_CERT_PATH') else omit) }}"
        cert_path: "{{ item.cert_path | default((lookup('env', 'DOCKER_CERT_PATH') + '/cert.pem')  if lookup('env', 'DOCKER_CERT_PATH') else omit) }}"
        key_path: "{{ item.key_path | default((lookup('env', 'DOCKER_CERT_PATH') + '/key.pem') if lookup('env', 'DOCKER_CERT_PATH') else omit) }}"
        tls_verify: "{{ item.tls_verify | default(lookup('env', 'DOCKER_TLS_VERIFY')) or false }}"
      with_items: "{{ platforms }}"
      when:
        - item.registry is defined
        - item.registry.credentials is defined
        - item.registry.credentials.username is defined
      no_log: true

    - name: Create Dockerfiles from image names
      template:
        # when using embedded playbooks the dockerfile is alonside them
        src: >-
          {%- if dockerfile_stats.results[i].stat.exists -%}
          {{ molecule_scenario_directory + '/' + (item.dockerfile | default( 'Dockerfile.j2')) }}
          {%- else -%}
          {{ playbook_dir + '/Dockerfile.j2' }}
          {%- endif -%}
        dest: "{{ molecule_ephemeral_directory }}/Dockerfile_{{ item.image | regex_replace('[^a-zA-Z0-9_]', '_') }}"
        mode: "0600"
      loop: "{{ platforms }}"
      loop_control:
        index_var: i
      when: not item.pre_build_image | default(false)
      register: platforms

    - name: Discover local Docker images
      docker_image_info:
        name: "molecule_local/{{ item.item.name }}"
        docker_host: "{{ item.item.docker_host | default(lookup('env', 'DOCKER_HOST') or 'unix://var/run/docker.sock') }}"
        cacert_path: "{{ item.cacert_path | default((lookup('env', 'DOCKER_CERT_PATH') + '/ca.pem') if lookup('env', 'DOCKER_CERT_PATH') else omit) }}"
        cert_path: "{{ item.cert_path | default((lookup('env', 'DOCKER_CERT_PATH') + '/cert.pem')  if lookup('env', 'DOCKER_CERT_PATH') else omit) }}"
        key_path: "{{ item.key_path | default((lookup('env', 'DOCKER_CERT_PATH') + '/key.pem') if lookup('env', 'DOCKER_CERT_PATH') else omit) }}"
        tls_verify: "{{ item.tls_verify | default(lookup('env', 'DOCKER_TLS_VERIFY')) or false }}"
      with_items: "{{ platforms.results }}"
      when:
        - not item.pre_build_image | default(false)
      register: docker_images

    - name: Build an Ansible compatible image (new)  # noqa: no-handler
      when:
        - platforms.changed or docker_images.results | map(attribute='images') | select('equalto', []) | list | count >= 0
        - not item.item.pre_build_image | default(false)
      docker_image:
        build:
          path: "{{ molecule_ephemeral_directory }}"
          dockerfile: "{{ item.invocation.module_args.dest }}"
          pull: "{{ item.item.pull | default(true) }}"
          network: "{{ item.item.network_mode | default(omit) }}"
          args: "{{ item.item.buildargs | default(omit) }}"
        name: "molecule_local/{{ item.item.image }}"
        docker_host: "{{ item.item.docker_host | default(lookup('env', 'DOCKER_HOST') or 'unix://var/run/docker.sock') }}"
        cacert_path: "{{ item.cacert_path | default((lookup('env', 'DOCKER_CERT_PATH') + '/ca.pem') if lookup('env', 'DOCKER_CERT_PATH') else omit) }}"
        cert_path: "{{ item.cert_path | default((lookup('env', 'DOCKER_CERT_PATH') + '/cert.pem')  if lookup('env', 'DOCKER_CERT_PATH') else omit) }}"
        key_path: "{{ item.key_path | default((lookup('env', 'DOCKER_CERT_PATH') + '/key.pem') if lookup('env', 'DOCKER_CERT_PATH') else omit) }}"
        tls_verify: "{{ item.tls_verify | default(lookup('env', 'DOCKER_TLS_VERIFY')) or false }}"
        force_source: "{{ item.item.force | default(true) }}"
        source: build
      with_items: "{{ platforms.results }}"
      loop_control:
        label: "molecule_local/{{ item.item.image }}"
      no_log: false
      register: result
      until: result is not failed
      retries: 3
      delay: 30

    - name: Create docker network(s)
      include_tasks: tasks/create_network.yml
      with_items: "{{ platforms | molecule_get_docker_networks(molecule_labels) }}"
      loop_control:
        label: "{{ item.name }}"
      no_log: false

    - name: Determine the CMD directives
      set_fact:
        command_directives_dict: >-
          {{ command_directives_dict | default({}) |
             combine({ item.name: item.command | default('bash -c "while true; do sleep 10000; done"') })
          }}
      with_items: "{{ platforms }}"
      when: item.override_command | default(true)

    - name: Create molecule instance(s)
      docker_container:
        name: "{{ item.name }}"
        docker_host: "{{ item.docker_host | default(lookup('env', 'DOCKER_HOST') or 'unix://var/run/docker.sock') }}"
        cacert_path: "{{ item.cacert_path | default((lookup('env', 'DOCKER_CERT_PATH') + '/ca.pem') if lookup('env', 'DOCKER_CERT_PATH') else omit) }}"
        cert_path: "{{ item.cert_path | default((lookup('env', 'DOCKER_CERT_PATH') + '/cert.pem')  if lookup('env', 'DOCKER_CERT_PATH') else omit) }}"
        key_path: "{{ item.key_path | default((lookup('env', 'DOCKER_CERT_PATH') + '/key.pem') if lookup('env', 'DOCKER_CERT_PATH') else omit) }}"
        tls_verify: "{{ item.tls_verify | default(lookup('env', 'DOCKER_TLS_VERIFY')) or false }}"
        hostname: "{{ item.hostname | default(item.name) }}"
        image: "{{ item.pre_build_image | default(false) | ternary('', 'molecule_local/') }}{{ item.image }}"
        pull: "{{ item.pull | default(omit) }}"
        memory: "{{ item.memory | default(omit) }}"
        memory_swap: "{{ item.memory_swap | default(omit) }}"
        state: started
        recreate: false
        log_driver: json-file
        command: "{{ (command_directives_dict | default({}))[item.name] | default(omit) }}"
        user: "{{ item.user | default(omit) }}"
        pid_mode: "{{ item.pid_mode | default(omit) }}"
        privileged: "{{ item.privileged | default(omit) }}"
        security_opts: "{{ item.security_opts | default(omit) }}"
        devices: "{{ item.devices | default(omit) }}"
        links: "{{ item.links | default(omit) }}"
        volumes: "{{ item.volumes | default(omit) }}"
        mounts: "{{ item.mounts | default(omit) }}"
        tmpfs: "{{ item.tmpfs | default(omit) }}"
        capabilities: "{{ item.capabilities | default(omit) }}"
        sysctls: "{{ item.sysctls | default(omit) }}"
        exposed_ports: "{{ item.exposed_ports | default(omit) }}"
        published_ports: "{{ item.published_ports | default(omit) }}"
        ulimits: "{{ item.ulimits | default(omit) }}"
        networks: "{{ item.networks | default(omit) }}"
        network_mode: "{{ item.network_mode | default(omit) }}"
        networks_cli_compatible: "{{ item.networks_cli_compatible | default(true) }}"
        purge_networks: "{{ item.purge_networks | default(omit) }}"
        dns_servers: "{{ item.dns_servers | default(omit) }}"
        etc_hosts: "{{ item.etc_hosts | default(omit) }}"
        env: "{{ item.env | default(omit) }}"
        restart_policy: "{{ item.restart_policy | default(omit) }}"
        restart_retries: "{{ item.restart_retries | default(omit) }}"
        tty: "{{ item.tty | default(omit) }}"
        labels: "{{ molecule_labels | combine(item.labels | default({})) }}"
        container_default_behavior: "{{ item.container_default_behavior |
                                        default('compatibility' if ansible_version.full is version_compare('2.10', '>=') else omit) }}"
        stop_signal: "{{ item.stop_signal | default(omit) }}"
        kill_signal: "{{ item.kill_signal | default(omit) }}"
      register: server
      with_items: "{{ platforms }}"
      loop_control:
        label: "{{ item.name }}"
      no_log: false
      async: 7200
      poll: 0

    - name: Wait for instance(s) creation to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: docker_jobs
      until: docker_jobs.finished
      retries: 300
      with_items: "{{ server.results }}"

```
