### ISSUE TITLE
How i can specify architecture x64 on Apple Silicon (aarch64)?

### ISSUE THREAD

**Issue by anshibanov** [ansible-community/molecule-docker#114]
For now in my molecule/default/molecule.yml i have:

```
platforms:
  - name: instance
    image: jrei/systemd-ubuntu:20.04
    pre_build_image: true
```
I run on aarch64 and molecule starting images with aarch64 architecture. But i want x64 (this image have this arch). How i can do it?

**Comment by CorbanR** [comment]
You should be able to set `DOCKER_DEFAULT_PLATFORM=linux/amd64`. However I can't seem to get that working when running `molecule test`. I have however worked around the issue by specifying the  images `sha256`.  See https://hub.docker.com/layers/ubuntu/library/ubuntu/20.04/images/sha256-7cc0576c7c0ec2384de5cbf245f41567e922aab1b075f3e8ad565f508032df17?context=explore 


example: molecule.yml
```
---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # Below sha256 is for the `linux/amd64` architecture 
  - name: ubuntu2004
     image: ubuntu:20.04@sha256:7cc0576c7c0ec2384de5cbf245f41567e922aab1b075f3e8ad565f508032df17
```
