### ISSUE TITLE
create.yml and destroy.yml logs passwords

### ISSUE THREAD

**Issue by szzsolt** [ansible-community/molecule-docker#121]
Hello

I am trying to run a scenario using a password protected private registry, part of the molecule.yml file listed below:

```
platforms:
  - name: instance
    image: registry.domain.com:/image:latest
    registry:
      url: registry.domain.com
      credentials:
        username: $REPO_USER
        password: $REPO_PASSWORD
```

Running molecule create and/or molecule destroy will log the passwords to the console. 

This seems to be because in both create.yml and destroy.yml there are no_log: false options set in multiple places, one example is here:

https://github.com/ansible-community/molecule-docker/blob/4c8fbd68161efebcdceb78a3cca787991bbece20/src/molecule_docker/playbooks/create.yml#L87
