### ISSUE TITLE
exposed port issue with docker module

### ISSUE THREAD

**Issue by spham** [ansible-community/molecule-docker#130]
# Issue Type

exposed port not work

```
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    exposed_ports:
      - "80:80"
      - "8000:8000"
    published_ports:
      - "80:80"
      - "8000:8000"
```

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
```

Molecule installation method (one of):

python3 -m pip install molecule ansible-core
python3 -m pip install molecule-goss
python3 -m pip install molecule-docker

Ansible installation method (one of):

```
molecule --version

molecule 3.5.2 using python 3.9 
    ansible:2.11.6
    delegated:3.5.2 from molecule
    docker:1.1.0 from molecule_docker requiring collections: community.docker>=1.9.1
    hetznercloud:1.3.0 from molecule_hetznercloud
    vagrant:0.6.3 from molecule_vagrant
```

Detail any linters or test runners used:

```
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    exposed_ports:
      - "8000:8000"
    published_ports:
      - "80:80"
      - "8000:8000"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: goss
```

# Desired Behavior

I wish reach port from outside container

# Actual Behaviour

Connection refused

  curl -I 127.0.0.1:8000
  curl: (7) Failed to connect to 127.0.0.1 port 8000: Connexion refusée
