### ISSUE TITLE
Remove DOCKER_HOST parameter from ansible_docker_extra_args

### ISSUE THREAD

**Issue by FlxPeters** [ansible-community/molecule-docker#137]
# Issue Type

Unexpected behavior / question

# Molecule and Ansible details 

```
molecule --version
molecule 3.6.1 using python 3.10 
    ansible:2.12.4
    delegated:3.6.1 from molecule
    docker:1.1.0 from molecule_docker requiring collections: community.docker>=1.9.1
```

# Desired Behavior

Molecule Docker should use the `DOCKER_HOST` from the environment instead of set it as `ansible_docker_extra_args`or should at least allow to override this behaviour.

# Actual Behaviour

When running Molecule with [Podman as Docker replacement ](https://www.redhat.com/sysadmin/podman-docker-compose)it fails with the following message: 

```
FAILED! => {"msg": "Docker version check (['/usr/bin/docker', '-H=unix:///run/user/1000/podman/podman.sock', 'version', '--format', \"'{{.Server.Version}}'\"]) failed: Error: unknown shorthand flag: 'H' in -H=unix:///run/user/1000/podman/podman.sock\n"}
```

The root cause is that the driver adds the `DOCKER_HOST` as a parameter with `-H` to `ansible_docker_extra_args`.
https://github.com/ansible-community/molecule-docker/blob/3441d5a1e9e8980170796b66289ed53bf62f8596/src/molecule_docker/driver.py#L224
The Podman Docker replacement does not support this flag. 

When i remove this specific line from the inventory everything works as expected because Docker/Podman pulls the config from the environment. 

**Is there a concrete reason to set the flag explicitly and not use the environment variable?** 
Otherwise i would recommend to remove this behavior and use the environment variable which works for both implementations. 

Here's an example of the problematic part of the generated inventory. 
```
# Molecule managed
---
all:
  hosts:
    instance-vault-agent: &id001
      ansible_connection: community.docker.docker
     # This line is the root cause - remove it and it works
      ansible_docker_extra_args: -H=unix:///run/user/1000/podman/podman.sock
 ```

Edit: This is an corner case where podman socket is running as user service to have rootless Docker over Podman.
https://major.io/2021/07/09/rootless-container-management-with-docker-compose-and-podman/
But the question is still the same, why is there an explicit config for the docker host?
