### ISSUE TITLE
Latest release depends on an alpha version of molecule

### ISSUE THREAD

**Issue by bendem** [ansible-community/molecule-docker#29]
Same as https://github.com/ansible-community/molecule-vagrant/issues/82

https://github.com/ansible-community/molecule-docker/blob/4b6e677878dd0734c1f769fca28c9207e26560dd/setup.cfg#L67

**Comment by ssbarnea** [comment]
I am aware of this and it will remain like this until molecule will make a new release. If, for some reason, you cannot use the pre-release version of molecule, you can use requirement constraints to avoid it.

**Comment by bendem** [comment]
Right, but in the meantime, since molecule does not depend on specific versions of molecule-docker, `pipenv install molecule[docker]==3.1.5` fails since it gets the latest `molecule-docker` which depends on a higher version of molecule.
That's really broken. I fixed it with constraints, but it's a really weird dependency graph state to be in.

```toml
[dev-packages]
"molecule[lint]" = "==3.1.5"
"molecule-docker" = ">=0.2.4,!=0.3.3"
molecule-vagrant = ">=0.3,!=0.5"

#
# include ansible here, otherwise the latest version gets pulled in because version
# constraints are not shared across dev and runtime.
#                         - bendem
#
ansible = ">=2.9,<3,<2.10"

[packages]
ansible = ">=2.9,<3,<2.10"
passlib = ">=1.7,<1.8"
```
