### ISSUE TITLE
Module unable to decode valid JSON on stdin.

### ISSUE THREAD

**Issue by Madic-** [ansible-community/molecule-docker#42]
When running **molecule create** the task "Discover local Docker images" crashes with "Error: Module unable to decode valid JSON on stdin.  Unable to figure out what parameters were passed".

```
TASK [Discover local Docker images] ********************************************
failed: [localhost] (item={'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False', 'item': {'image': 'geerlingguy/docker-centos7-ansible:latest', 'name': 'instance', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}, 'ansible_loop_var': 'item', 'i': 0, 'ansible_index_var': 'i'}) => {"ansible_loop_var": "item", "changed": false, "item": {"ansible_index_var": "i", "ansible_loop_var": "item", "changed": false, "i": 0, "item": {"image": "geerlingguy/docker-centos7-ansible:latest", "name": "instance", "pre_build_image": true, "privileged": true, "volumes": ["/sys/fs/cgroup:/sys/fs/cgroup:ro"]}, "skip_reason": "Conditional result was False", "skipped": true}, "msg": "Error: Module unable to decode valid JSON on stdin.  Unable to figure out what parameters were passed"}
```

molecule.yml
```yml
---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  export ANSIBLE_ROLES_PATH=${MOLECULE_PROJECT_DIRECTORY}/.
  yamllint -c .yamllint .
  ansible-lint -c .ansible-lint playbook.yml
platforms:
  - name: instance
    image: "geerlingguy/docker-centos7-ansible:latest"
    #command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  #config_options:
  #  defaults:
  #    interpreter_python: auto_silent
  #    callback_whitelist: profile_tasks, timer, yaml
    #connection:
    #  pipelining: true
  #env:
  #  PY_COLORS: 1
verifier:
  name: ansible

```
```shell
molecule --version
molecule 3.2.3 using python 3.9
    ansible:2.10.6
    delegated:3.2.3 from molecule
    docker:0.2.4 from molecule_docker
docker --version
Docker version 19.03.14, build 5eb3275d40
```
