### ISSUE TITLE
Unnecessary warnings when creating/deleting docker networks

### ISSUE THREAD

**Issue by mtpettyp** [ansible-community/molecule-docker#47]
With the following `molecule.yml`:
```
---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-focal-test
    image: ubuntu:focal
    dockerfile: Dockerfile.j2
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"
    networks:
      - name: test
        ipv4_address: "10.30.50.12"
```

Running `molecule create` gives:
```
TASK [Create docker network(s)] ************************************************
[WARNING]: Using a variable for a task's 'args' is unsafe in some situations
(see
https://docs.ansible.com/ansible/devel/reference_appendices/faq.html#argsplat-
unsafe)
changed: [localhost] => (item=test)
```
And `molecule destroy` gives:
```
TASK [Delete docker network(s)] ************************************************
[WARNING]: Using a variable for a task's 'args' is unsafe in some situations
(see
https://docs.ansible.com/ansible/devel/reference_appendices/faq.html#argsplat-
unsafe)
changed: [localhost] => (item=test)
```
This is because of the use of `args` in `create.yml` and `destroy.yml`
```
    - name: Create docker network(s)
      action: docker_network
      args: "{{ item }}"
      with_items: "{{ molecule_yml.platforms | molecule_get_docker_networks('present', molecule_labels) }}"
      loop_control:
        label: "{{ item.name }}"
      no_log: false
```

Rewriting the `Create docker network(s)` and `Delete docker network(s)` tasks to use the `docker_network` plugin directly (similarly to how `Create molecule instance(s)` uses `docker_container`) would clean up these unnecessary warnings.
