### ISSUE TITLE
Connection between docker instances

### ISSUE THREAD

**Issue by walbertus** [ansible-community/molecule-docker#68]
Is it possible to do connections between different docker instances?
If it's there, can you point out the documentation or how-to? I can't find it anywhere

e.g:
```yaml
platforms:
  - name: pg-master
    image: ubuntu:18.04
    provision: True
  - name: pg-replica
    image: ubuntu:18.04
    provision: True
```

I need the `pg-replica` to be able to connect to `pg-master`

If it's not supported, any clue on which part should I look when I want to raise a PR? Thanks

**Comment by 1moere1** [comment]
This is really needed for many use-cases. One example is testing Active Directory Setup Roles.

**Comment by hassenius** [comment]
I've just wrestled with this same problem, and after some pointers from the folks over at IRC found the solution in this

```yaml
platforms:
  - name: ${MOLECULE_SCENARIO_NAME}-pdns
    image: pdns-alpine:4.2.3
    docker_networks: 
      - name: ${MOLECULE_SCENARIO_NAME}
    publish_all_ports: true
    env:
      PDNS_LOG_LEVEL: "5"
      PDNS_WEBSERVER_ALLOWED_FROM: 0.0.0.0/0
    pre_build_image: yes
    override_command: no
  - name: ${MOLECULE_SCENARIO_NAME}-runner
    image: python:3.9-alpine-requests
    docker_networks: 
      - name: ${MOLECULE_SCENARIO_NAME}
    pre_build_image: true
    command: sleep infinity
```

and then I can do things like 

`nslookup -type=a myhost.testzone {{ groups['all'][0] }}`

and

```yaml
- name: Converge
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Create test zone for a records"
      community.docker.docker_container_exec:
        container: "{{ groups['all'][0] }}"
```

Basically since the containers are in a custom docker network they can do service discovery based on container names, etc....
